# Generated by Django 5.1.1 on 2026-09-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_lvdtprobemaster_nominal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gst_no',
            field=models.CharField(max_length=50),
        ),
    ]
